updates to pod and dk

diff --git a/build_pod b/build_pod
--- a/build_pod
+++ b/build_pod
@@ -5,6 +5,20 @@
 source ks_config.sh
 source telhub.sh
 
+funcHandleReturnCode() {
+
+  returnCode=$1
+  msg=$2
+
+  if (( returnCode != 0 ));then
+      echo ${returnCode}
+      echo "FAILED!!! ${msg}"
+      exit ${returnCode}
+  else
+      echo "Success: ${msg}"
+  fi
+}
+
 LOCAL_PATH=$(pwd)
 
 if [ ! -z "$1" ] && [ "$1" != "skip" ]; then
@@ -45,9 +59,13 @@ echo "SERVICE_NAME $SERVICE_NAME";
 echo "NAMESPACE $NAMESPACE";
 echo "HELM_DEPLOYMENT_NAME $HELM_DEPLOYMENT_NAME";
 
-$DOCKER build -f Dockerfile -t ${SERVICE_NAME}:latest .
-$DOCKER tag ${SERVICE_NAME}:latest $DIR:$DOCKER_TAG
+$DOCKER build --tag=${SERVICE_NAME}:latest .
+funcHandleReturnCode $? "Build Docker image"
+
 $DOCKER tag ${SERVICE_NAME}:latest $DIR:latest
+$DOCKER tag ${SERVICE_NAME}:latest $DIR:$DOCKER_TAG
+$DOCKER tag ${SERVICE_NAME}:latest $SERVICE_NAME:$DOCKER_TAG
+funcHandleReturnCode $? "Tag Docker image"
 
 kubectl config use-context $CONTEXT
 
@@ -56,7 +74,9 @@ RELEASE_NAME_LISTING=$(helm ls ${HELM_DEPLOYMENT_NAME} --namespace ${NAMESPACE} 
 ## Check if Helm is installed otherwise upgrade
 if [[ $RELEASE_NAME_LISTING == *"${HELM_DEPLOYMENT_NAME}"*"${NAMESPACE}"* ]]
 then
-	helm upgrade --namespace ${NAMESPACE} ${HELM_DEPLOYMENT_NAME} "${CHARTS}/${SERVICE_NAME}"  --set image.repository=${DIR},image.tag=${DOCKER_TAG},image.pullPolicy=IfNotPresent,localPath=${LOCAL_PATH} --recreate-pods
+	helm upgrade --namespace ${NAMESPACE} ${HELM_DEPLOYMENT_NAME} "${CHARTS}/${SERVICE_NAME}"  --set image.repository=${SERVICE_NAME},image.tag=${DOCKER_TAG},image.pullPolicy=IfNotPresent,localPath=${LOCAL_PATH} --recreate-pods
 else
-	helm install --namespace ${NAMESPACE} "${CHARTS}/${SERVICE_NAME}" --name=${HELM_DEPLOYMENT_NAME} --set image.repository=${DIR},image.tag=${DOCKER_TAG},image.pullPolicy=IfNotPresent,localPath=${LOCAL_PATH}
+	helm install --namespace ${NAMESPACE} "${CHARTS}/${SERVICE_NAME}" --name=${HELM_DEPLOYMENT_NAME} --set image.repository=${SERVICE_NAME},image.tag=${DOCKER_TAG},image.pullPolicy=IfNotPresent,localPath=${LOCAL_PATH}
 fi
+
+funcHandleReturnCode $? "Helm"
